language: python

python:
  - "3.8"
  - "3.7"

before_install:
  - sudo apt-get -y install ledger
  - python --version
  - pip install -U pip
  - pip install -U coverage
  - pip install -U poetry

# command to install dependencies
install:
  - poetry install
# command to run tests
script:
  - pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
